version: '3.8'

services:
    ctx:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ctx-debug
        volumes:
            - .:/app
            - ./xdebug_traces:/app/xdebug_traces
        working_dir: /app
        environment:
            XDEBUG_MODE: "debug"  # Enable debug and trace
            #XDEBUG_TRIGGER: "1"  # Always trigger tracing
        tty: true
        stdin_open: true
        command: php app.php
